eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
spring:  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reactive-mongo
          uri: http://localhost:8087/api/v1
          predicates:
            - Path=/api/**
